/**
 * AGENTS.md export (v1.6.0, ADR-0020). For the Codex target, a capsule can be
 * persisted as an `AGENTS.md` file at the project root — the convention Codex
 * (and other agents) read on startup.
 *
 * Safety contract:
 *   - Only write when the caller explicitly asks (the CLI `--agents-md` flag).
 *   - Never overwrite an existing AGENTS.md unless `force` is set.
 *   - Always include a generated header so humans know it is Kairo-produced.
 *
 * Pure assembly + a single guarded write. The content is a capsule plus a thin
 * AGENTS.md frame; secrets are already redacted by the renderer.
 */

import { existsSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { CapsuleProjection, RenderedCapsule } from './capsuleTypes.js';

export interface AgentsMdResult {
  path: string;
  written: boolean;
  /** Set when the write was refused because the file exists and force was false. */
  refusedReason?: string;
}

const GENERATED_HEADER =
  '<!-- Generated by Kairo Atlas Capsule. Regenerate with: kairo capsule --target codex --agents-md.\n' +
  '     This is a continuation package, not a guarantee — verify before risky edits. -->';

/** Assemble the AGENTS.md body from a rendered capsule + its projection. */
export function buildAgentsMd(rendered: RenderedCapsule, projection: CapsuleProjection): string {
  const L: string[] = [];
  L.push(GENERATED_HEADER);
  L.push('');
  L.push('# AGENTS.md');
  L.push('');
  L.push(
    'This file orients an AI coding agent continuing work on this repository. It was ' +
      'generated by Kairo from the latest checkpoint and architecture projection. It ' +
      'reduces unnecessary rescanning by pointing you at what changed and what to read ' +
      'first — it is a trusted starting point, not a replacement for validation.',
  );
  L.push('');
  // The rendered capsule already contains the structured continuation package.
  L.push(rendered.text);
  L.push('');
  L.push('## Continuation instructions');
  L.push('- Open the files under **Read first** before broad exploration.');
  L.push('- Treat **Safe to skip initially** as safe to skip unless you detect a mismatch.');
  if (projection.doNotTouch.length > 0) {
    L.push('- Respect the **Do not touch** list above; those paths are high risk.');
  }
  L.push('- Run the verification commands before relying on prior changes.');
  return L.join('\n');
}

/**
 * Guarded write of AGENTS.md to the project root. Refuses to overwrite unless
 * `force`. Returns the outcome; never throws on a refusal.
 */
export async function writeAgentsMd(
  projectRoot: string,
  body: string,
  opts: { force?: boolean } = {},
): Promise<AgentsMdResult> {
  const path = join(projectRoot, 'AGENTS.md');
  if (existsSync(path) && !opts.force) {
    return {
      path,
      written: false,
      refusedReason: 'AGENTS.md already exists. Pass --force to overwrite.',
    };
  }
  await writeFile(path, body.endsWith('\n') ? body : body + '\n', 'utf8');
  return { path, written: true };
}
